/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.areopuerto.GUI;

import java.awt.HeadlessException;
import java.util.Map;
import javax.swing.JFrame;
import poo.areopuerto.*;
import poo.areopuerto.controlers.AereopuertoController;



/**
 *
 * @author erick
 */
public class GestionAvionesFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GestionAvionesFrame.class.getName());

    private AereopuertoController controlador;
    private Aereopuerto aereopuertoActual;
    private Avion a; //Clase avion que facilita la busqueda y actualizacion de los aviones
    
    public GestionAvionesFrame(AereopuertoController controlador, Aereopuerto aereopuerto) throws HeadlessException {
        this.controlador = controlador;
        this.aereopuertoActual = aereopuerto;
        initComponents();
        PB.setVisible(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    
    /**
     * Creates new form GestionAvionesFrame
     */
    public GestionAvionesFrame() {
        PB.setVisible(false);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtPlacaAvion1 = new javax.swing.JTextField();
        MenuAviones = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jToolBar3 = new javax.swing.JToolBar();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtPlacaCarga = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtMarcaCarga = new javax.swing.JTextField();
        txtModeloCarga = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCapacidadCarga = new javax.swing.JTextField();
        btnGuardarAvionCarga = new javax.swing.JButton();
        jToolBar4 = new javax.swing.JToolBar();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtPlacaPasajeros = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtMarcaPasajeros = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtModeloPasajeros = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtCapacidadPasajeros = new javax.swing.JTextField();
        btnGuardarAvionPasajeros = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtBuscarAvion = new javax.swing.JTextField();
        btnBuscarAvion = new javax.swing.JButton();
        PB = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtVariable = new javax.swing.JLabel();
        variableField = new javax.swing.JTextField();
        modeloField = new javax.swing.JTextField();
        marcaField = new javax.swing.JTextField();
        placaField = new javax.swing.JTextField();
        Actualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaAviones = new javax.swing.JTextArea();

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Placa del aeronave:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuAviones.setBackground(new java.awt.Color(51, 102, 153));
        MenuAviones.setForeground(new java.awt.Color(255, 255, 255));
        MenuAviones.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        MenuAviones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaAviones(evt);
            }
        });

        jToolBar1.setRollover(true);

        jTabbedPane2.setBackground(new java.awt.Color(51, 102, 153));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jToolBar3.setRollover(true);

        jPanel4.setBackground(new java.awt.Color(51, 102, 153));
        jPanel4.setFocusable(false);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Placa del Aeronave: ");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Modelo del Aeronave: ");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Marca del Aeronave: ");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Capacidad de carga (en kg): ");

        btnGuardarAvionCarga.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuardarAvionCarga.setForeground(new java.awt.Color(51, 102, 153));
        btnGuardarAvionCarga.setText("Guardar");
        btnGuardarAvionCarga.addActionListener(this::btnGuardarAvionCargaActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCapacidadCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPlacaCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMarcaCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModeloCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnGuardarAvionCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPlacaCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtMarcaCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtModeloCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCapacidadCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarAvionCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar3.add(jPanel4);

        jTabbedPane2.addTab("Avion de Carga", jToolBar3);

        jToolBar4.setRollover(true);

        jPanel7.setBackground(new java.awt.Color(51, 102, 153));
        jPanel7.setFocusable(false);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Placa del Aeronave: ");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Marca del Aeronave: ");

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Modelo del Aeronave: ");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Capacidad de Pasajeros : ");

        btnGuardarAvionPasajeros.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGuardarAvionPasajeros.setForeground(new java.awt.Color(51, 102, 153));
        btnGuardarAvionPasajeros.setText("Guardar");
        btnGuardarAvionPasajeros.addActionListener(this::btnGuardarAvionPasajerosActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlacaPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarcaPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModeloPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btnGuardarAvionPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txtCapacidadPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtPlacaPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtMarcaPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtModeloPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtCapacidadPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarAvionPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToolBar4.add(jPanel7);

        jTabbedPane2.addTab("Avion Comercial", jToolBar4);

        jToolBar1.add(jTabbedPane2);

        MenuAviones.addTab("Registrar Aviones", jToolBar1);

        jToolBar2.setRollover(true);

        jPanel2.setBackground(new java.awt.Color(51, 102, 153));
        jPanel2.setFocusable(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(389, 300));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Porfavor introduzca la id de la aeronave: ");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 20));
        jPanel2.add(txtBuscarAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 80, -1));

        btnBuscarAvion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBuscarAvion.setForeground(new java.awt.Color(51, 102, 153));
        btnBuscarAvion.setText("Buscar");
        btnBuscarAvion.addActionListener(this::btnBuscarAvionActionPerformed);
        jPanel2.add(btnBuscarAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        PB.setFocusable(false);

        jLabel1.setText("Placa");

        jLabel2.setText("Marca");

        jLabel3.setText("Modelo");

        txtVariable.setText("Carga");

        variableField.setPreferredSize(new java.awt.Dimension(100, 22));

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(this::ActualizarActionPerformed);

        javax.swing.GroupLayout PBLayout = new javax.swing.GroupLayout(PB);
        PB.setLayout(PBLayout);
        PBLayout.setHorizontalGroup(
            PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PBLayout.createSequentialGroup()
                        .addComponent(txtVariable)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PBLayout.createSequentialGroup()
                        .addGroup(PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)))
                .addGroup(PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PBLayout.createSequentialGroup()
                        .addGroup(PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(marcaField)
                            .addComponent(modeloField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(Actualizar))
                    .addGroup(PBLayout.createSequentialGroup()
                        .addGroup(PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(placaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(variableField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PBLayout.setVerticalGroup(
            PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(placaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PBLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(marcaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(modeloField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PBLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Actualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(variableField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVariable))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.add(PB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 160));

        jToolBar2.add(jPanel2);

        MenuAviones.addTab("Editar Aviones", jToolBar2);

        jPanel3.setBackground(new java.awt.Color(51, 102, 153));
        jPanel3.setFocusable(false);

        ListaAviones.setColumns(20);
        ListaAviones.setRows(5);
        ListaAviones.setFocusable(false);
        jScrollPane1.setViewportView(ListaAviones);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        MenuAviones.addTab("Listar Aviones", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuAviones, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuAviones, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarAvionCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAvionCargaActionPerformed
        String placa = txtPlacaCarga.getText();
        String modelo = txtModeloCarga.getText();
        String marca = txtMarcaCarga.getText();
        String pesoMax= txtCapacidadCarga.getText();
        
        int peso;
        
        try {
            peso=Integer.parseInt(pesoMax);
        }catch(Exception e) {
            System.out.println("Error en el peso debe ser entero positivo");
            return;
        }
 
        Avion a = new AvionDeCarga(placa, marca, modelo, aereopuertoActual.getId(), false, peso);
        controlador.agregarAvion(a);
        Notificador.info("Avion de carga Creado Correctamente");
    }//GEN-LAST:event_btnGuardarAvionCargaActionPerformed

    private void btnGuardarAvionPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAvionPasajerosActionPerformed
        String placa = txtPlacaPasajeros.getText();
        String marca = txtMarcaPasajeros.getText();
        String modelo = txtModeloPasajeros.getText();
        String capMax= txtCapacidadPasajeros.getText();

        int cap;
        try {
            cap=Integer.parseInt(capMax);
        }catch(Exception e) {
            System.out.println("Error en el peso debe ser entero positivo");
            return;
        }
        Avion a = new AvionPasajeros(placa, marca, modelo, aereopuertoActual.getId(), false, cap);
        controlador.agregarAvion(a);
        
        Notificador.info("Avion de pasajeros Creado Correctamente");
        

    }//GEN-LAST:event_btnGuardarAvionPasajerosActionPerformed

    private void btnBuscarAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAvionActionPerformed
        String idBusqueda = txtBuscarAvion.getText();
        int idInt;
        try {
            idInt=Integer.parseInt(idBusqueda);
        } catch (Exception e) {
            Notificador.info("No existe un avion con ese id");
            return;
        }
        a=controlador.getAvion(idInt);
        if(a==null) return;
        PB.setVisible(true);
        placaField.setText(a.getPlaca());
        marcaField.setText(a.getMarca());
        modeloField.setText(a.getModelo());
        String clase = a.getClass().getSimpleName();
        if(clase.equals("AvionDeCarga"))txtVariable.setText("CargaMax");
        else txtVariable.setText("PasajerosMax");

    }//GEN-LAST:event_btnBuscarAvionActionPerformed

    private void ListaAviones(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaAviones
        int menuSeleccionado=MenuAviones.getSelectedIndex();
        System.out.println(menuSeleccionado);
        if(menuSeleccionado==1)PB.setVisible(false);
        if(menuSeleccionado==2){
            ListaAviones.setText("");
            for (Map.Entry<Integer, Avion> entry : controlador.getAviones().entrySet()) {
                ListaAviones.append("[" + entry.getKey() + "] " + entry.getValue()+"\n");
            }
            PB.setVisible(false);
        }
    }//GEN-LAST:event_ListaAviones

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        String placa = placaField.getText();
        String marca =marcaField.getText();
        String modelo=modeloField.getText();
        String variable=variableField.getText();
        String clase = a.getClass().getSimpleName();
        Avion actAvion;
        int intVar;
        try {
            intVar=Integer.parseInt(variable);
        } catch (Exception e) {
            Notificador.info("El valor debe ser un entero positivo");
            return;
        }
        //Aqui podria usar el a que tengo del objeto y cambiar sus propiedades pero esto es mas
        //corto no mas eficiente
        if(clase.equals("AvionDeCarga")){
            actAvion=new AvionDeCarga(placa, marca ,modelo,aereopuertoActual.getId(),false,intVar);
        }else{
            actAvion=new AvionPasajeros(placa, marca, modelo,aereopuertoActual.getId(),false,intVar);
        }
        actAvion.setId(a.getId());
        controlador.actualizarAvion(actAvion);
        
        
        
    }//GEN-LAST:event_ActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GestionAvionesFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JTextArea ListaAviones;
    private javax.swing.JTabbedPane MenuAviones;
    private javax.swing.JPanel PB;
    private javax.swing.JButton btnBuscarAvion;
    private javax.swing.JButton btnGuardarAvionCarga;
    private javax.swing.JButton btnGuardarAvionPasajeros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JTextField marcaField;
    private javax.swing.JTextField modeloField;
    private javax.swing.JTextField placaField;
    javax.swing.JTextField txtBuscarAvion;
    private javax.swing.JTextField txtCapacidadCarga;
    private javax.swing.JTextField txtCapacidadPasajeros;
    private javax.swing.JTextField txtMarcaCarga;
    private javax.swing.JTextField txtMarcaPasajeros;
    private javax.swing.JTextField txtModeloCarga;
    private javax.swing.JTextField txtModeloPasajeros;
    private javax.swing.JTextField txtPlacaAvion1;
    private javax.swing.JTextField txtPlacaCarga;
    private javax.swing.JTextField txtPlacaPasajeros;
    private javax.swing.JLabel txtVariable;
    private javax.swing.JTextField variableField;
    // End of variables declaration//GEN-END:variables
}

