/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.areopuerto.GUI;

import poo.areopuerto.Aereopuerto;
import poo.areopuerto.Avion;
import poo.areopuerto.AvionDeCarga;
import poo.areopuerto.AvionPasajeros;
import poo.areopuerto.models.AereopuertoModel;

/**
 *
 * @author erick
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuRegistrarAerolinea = new javax.swing.JMenuItem();
        menuListarAerolineas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCrearVuelo = new javax.swing.JMenuItem();
        menuConsultarVuelos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador de Vuelos - Sistema");
        setSize(new java.awt.Dimension(1000, 700));

        menuArchivo.setText("Archivo");

        menuSalir.setText("Salir");
        menuSalir.addActionListener(this::menuSalirActionPerformed);
        menuArchivo.add(menuSalir);

        jMenuBar1.add(menuArchivo);

        jMenu1.setText("Areolineas");

        menuRegistrarAerolinea.setText("Registrar Aerolínea");
        menuRegistrarAerolinea.addActionListener(this::menuRegistrarAerolineaActionPerformed);
        jMenu1.add(menuRegistrarAerolinea);

        menuListarAerolineas.setText("Listar Aerolíneas");
        jMenu1.add(menuListarAerolineas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vuelos");

        menuCrearVuelo.setText("Crear Vuelo");
        jMenu2.add(menuCrearVuelo);

        menuConsultarVuelos.setText("Consultar Vuelos");
        jMenu2.add(menuConsultarVuelos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuRegistrarAerolineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarAerolineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuRegistrarAerolineaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Aereopuerto AE = new Aereopuerto("Aere", 2, "Ecuador", "Quito", 2, true);
        AereopuertoModel A= new AereopuertoModel();
        Avion A1 = new AvionDeCarga("ABC", "DFG", "HIJG", true, 1234);
        Avion A2 = new AvionPasajeros("ABC", "DFG", "HIJG", true, 1234);
        A.agregar(A1.toString(), "avion.txt");
        A.agregar(A2.toString(), "avion.txt");
        A.agregar(AE.toString(), "aereopuerto.txt");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuConsultarVuelos;
    private javax.swing.JMenuItem menuCrearVuelo;
    private javax.swing.JMenuItem menuListarAerolineas;
    private javax.swing.JMenuItem menuRegistrarAerolinea;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables
}
