/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.areopuerto.GUI;

import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;

import poo.areopuerto.Aereolinea;
import poo.areopuerto.Aereopuerto;
import poo.areopuerto.Avion;
import poo.areopuerto.controlers.AereopuertoController;
import poo.areopuerto.models.AereopuertoModel;

/**
 *
 * @author erick
 */
public class MenuPrincipalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName());
    private final AereopuertoModel modelo;
    private Map<Integer,Aereopuerto> aereopuertos;
    private AereopuertoController controladorAct;

    /**
     * Creates new form MainFrame
     */
    public MenuPrincipalFrame() {
        //Mejoras usar un aereopuerto act ya que este incluye su controlador
        //Carga de datos
        aereopuertos= new HashMap<>();
        modelo= new AereopuertoModel();
        aereopuertos=modelo.cargarAereopuertos();
        modelo.cargarAviones(aereopuertos);
        modelo.cargarVuelos(aereopuertos);
        
        
        modelo.cargarAerolineas(aereopuertos);
        //Se asume que debe existir al menos un aereopuerto ya cargado en el sistema
        
        controladorAct=aereopuertos.get(1).getControlador(); //Se supone que empezamos administrando el aereopuerto 1
        initComponents();
        
        labelAereopuerto.setText("Administrando Aereopuerto: "+aereopuertos.get(1).getNombre());
        
        //Se declara los elementos de la lista de aereopuertos
        cbAviones.setModel(new DefaultComboBoxModel<Aereopuerto>(aereopuertos.values().toArray(new Aereopuerto[0])));
        
        //Carga de aereolineas en interface
        cbAviones.addActionListener(new java.awt.event.ActionListener(){        
            public void actionPerformed(java.awt.event.ActionEvent evt){
            // Se olbtiene el item seleccionado
            Aereopuerto seleccionado = (Aereopuerto) cbAviones.getSelectedItem();

                if (seleccionado != null) {
                    //Cambia el controlador a el aereopuerto seleccionado
                    controladorAct=seleccionado.getControlador();

                    //Muestra el aereopuerto que se esta editando
                    labelAereopuerto.setText("Administrando Aereopuerto: "+seleccionado.getNombre());
                }
            }
        });
        //Guardado al cerrar la ventana
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                modelo.escribirAereopuertos(aereopuertos);
                Map<Integer,Avion> aviones= new HashMap<>();
                Map<Integer,Aereolinea> aerolineas= new HashMap<>();
                //Pasa que el controlador borra todo el archivo antes de cargar lo que es aviones y aereolines
                //por lo que se debe realizar una sola carga de aviones y aereolines
                for (Aereopuerto aereopuerto : aereopuertos.values()) {
                    controladorAct = aereopuerto.getControlador();            
                    modelo.escribirVuelos(controladorAct.getVuelos());
                    aviones.putAll(controladorAct.getAviones());
                    aerolineas.putAll(controladorAct.getAereolineas());
                }
                modelo.escribirAviones(aviones);
                modelo.escribirAerolineas(aerolineas);
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        imgMenuAdmin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnGestionAreolineas = new javax.swing.JButton();
        btnGestionAviones = new javax.swing.JButton();
        btnGestionVuelos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbAviones = new javax.swing.JComboBox<>();
        labelAereopuerto = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador de Vuelos - Sistema");
        setSize(new java.awt.Dimension(1000, 700));

        jPanel4.setBackground(new java.awt.Color(51, 102, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione el Aeropuerto:");

        btnGestionAreolineas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnGestionAreolineas.setForeground(new java.awt.Color(51, 102, 153));
        btnGestionAreolineas.setText("GESTIONAR AREOLINEAS");
        btnGestionAreolineas.addActionListener(this::btnGestionAreolineasActionPerformed);

        btnGestionAviones.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnGestionAviones.setForeground(new java.awt.Color(51, 102, 153));
        btnGestionAviones.setText("GESTIONAR AVIONES");
        btnGestionAviones.addActionListener(this::btnGestionAvionesActionPerformed);

        btnGestionVuelos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnGestionVuelos.setForeground(new java.awt.Color(51, 102, 153));
        btnGestionVuelos.setText("GESTIONAR VUELOS");
        btnGestionVuelos.addActionListener(this::btnGestionVuelosActionPerformed);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BIENVENIDO AL ADMINISTRADOR ");

        cbAviones.addActionListener(this::cbAvionesActionPerformed);

        labelAereopuerto.setBackground(new java.awt.Color(51, 51, 51));
        labelAereopuerto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labelAereopuerto.setForeground(new java.awt.Color(255, 255, 255));
        labelAereopuerto.setText("Seleccione el Aeropuerto:");
        labelAereopuerto.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAviones, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGestionAreolineas)
                            .addComponent(btnGestionAviones, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGestionVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(imgMenuAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAereopuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAviones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelAereopuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGestionAreolineas)
                        .addGap(53, 53, 53)
                        .addComponent(btnGestionAviones)
                        .addGap(57, 57, 57)
                        .addComponent(btnGestionVuelos)
                        .addGap(75, 75, 75))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(imgMenuAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))))
        );

        menuArchivo.setText("Archivo");

        menuSalir.setText("Salir");
        menuSalir.addActionListener(this::menuSalirActionPerformed);
        menuArchivo.add(menuSalir);

        jMenuBar1.add(menuArchivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        modelo.escribirAereopuertos(aereopuertos);
        Map<Integer,Avion> aviones= new HashMap<>();
        Map<Integer,Aereolinea> aerolineas= new HashMap<>();
        for (Aereopuerto aereopuerto : aereopuertos.values()) {
            controladorAct = aereopuerto.getControlador();            
            modelo.escribirVuelos(controladorAct.getVuelos());
            aviones.putAll(controladorAct.getAviones());
            aerolineas.putAll(controladorAct.getAereolineas());
        }
        modelo.escribirAviones(aviones);
        modelo.escribirAerolineas(aerolineas);
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void btnGestionAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionAvionesActionPerformed
        GestionAvionesFrame gAvion = new GestionAvionesFrame(controladorAct, aereopuertos.get(1));
        gAvion.setVisible(true);
    }//GEN-LAST:event_btnGestionAvionesActionPerformed

    private void btnGestionVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionVuelosActionPerformed
        GesrtionarVuelosFrame gVuelos = new GesrtionarVuelosFrame(controladorAct, aereopuertos, aereopuertos.get(1).getId());
        gVuelos.setVisible(true);
    }//GEN-LAST:event_btnGestionVuelosActionPerformed

    private void btnGestionAreolineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionAreolineasActionPerformed

        GestionAerolíneasFrame gAreolinea = new GestionAerolíneasFrame(controladorAct, aereopuertos.get(1).getId());
        gAreolinea.setVisible(true);
    }//GEN-LAST:event_btnGestionAreolineasActionPerformed

    private void cbAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAvionesActionPerformed

    }//GEN-LAST:event_cbAvionesActionPerformed


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipalFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionAreolineas;
    private javax.swing.JButton btnGestionAviones;
    private javax.swing.JButton btnGestionVuelos;
    private javax.swing.JComboBox<Aereopuerto> cbAviones;
    private javax.swing.JLabel imgMenuAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelAereopuerto;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables
}
