/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.areopuerto.GUI;

import poo.areopuerto.Aereopuerto;
import poo.areopuerto.Avion;
import poo.areopuerto.AvionDeCarga;
import poo.areopuerto.AvionPasajeros;
import poo.areopuerto.models.AereopuertoModel;

/**
 *
 * @author erick
 */
public class MenuPrincipalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MenuPrincipalFrame() {
        initComponents();
    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        imgMenuAdmin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnGestionAreolineas = new javax.swing.JButton();
        btnGestionAviones = new javax.swing.JButton();
        btnGestionVuelos = new javax.swing.JButton();
        btnGestionAreopuertos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador de Vuelos - Sistema");
        setSize(new java.awt.Dimension(1000, 700));

        jPanel4.setBackground(new java.awt.Color(51, 102, 153));

        imgMenuAdmin.setIcon(new javax.swing.ImageIcon("C:\\Users\\erick\\Documents\\NetBeansProjects\\AereopuertoOficial\\src\\main\\java\\poo\\areopuerto\\GUI\\resoruces\\menuImage.png")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENIDO AL ADMINISTRADOR ");

        btnGestionAreolineas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnGestionAreolineas.setForeground(new java.awt.Color(51, 102, 153));
        btnGestionAreolineas.setText("GESTIONAR AREOLINEAS");
        btnGestionAreolineas.addActionListener(this::btnGestionAreolineasActionPerformed);

        btnGestionAviones.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnGestionAviones.setForeground(new java.awt.Color(51, 102, 153));
        btnGestionAviones.setText("GESTIONAR AVIONES");
        btnGestionAviones.addActionListener(this::btnGestionAvionesActionPerformed);

        btnGestionVuelos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnGestionVuelos.setForeground(new java.awt.Color(51, 102, 153));
        btnGestionVuelos.setText("GESTIONAR VUELOS");
        btnGestionVuelos.addActionListener(this::btnGestionVuelosActionPerformed);

        btnGestionAreopuertos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnGestionAreopuertos.setForeground(new java.awt.Color(51, 102, 153));
        btnGestionAreopuertos.setText("GESTIONAR AREOPUERTOS");
        btnGestionAreopuertos.addActionListener(this::btnGestionAreopuertosActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGestionAreopuertos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGestionAviones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGestionAreolineas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btnGestionVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgMenuAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnGestionAreolineas)
                        .addGap(64, 64, 64)
                        .addComponent(btnGestionAviones)
                        .addGap(65, 65, 65)
                        .addComponent(btnGestionVuelos)
                        .addGap(61, 61, 61)
                        .addComponent(btnGestionAreopuertos)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgMenuAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        menuArchivo.setText("Archivo");

        menuSalir.setText("Salir");
        menuSalir.addActionListener(this::menuSalirActionPerformed);
        menuArchivo.add(menuSalir);

        jMenuBar1.add(menuArchivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void btnGestionAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionAvionesActionPerformed
        GestionAvionesFrame gAvion = new GestionAvionesFrame();
        gAvion.setVisible(true);
    }//GEN-LAST:event_btnGestionAvionesActionPerformed

    private void btnGestionVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionVuelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionVuelosActionPerformed

    private void btnGestionAreopuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionAreopuertosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionAreopuertosActionPerformed

    private void btnGestionAreolineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionAreolineasActionPerformed
        GestionAerolíneasFrame gAreolinea = new GestionAerolíneasFrame();
        gAreolinea.setVisible(true);
    }//GEN-LAST:event_btnGestionAreolineasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Aereopuerto AE = new Aereopuerto("Aere", 2, "Ecuador", "Quito", 2, true);
        AereopuertoModel A= new AereopuertoModel();
        Avion A1 = new AvionDeCarga("ABC", "DFG", "HIJG", true, 1234);
        Avion A2 = new AvionPasajeros("ABC", "DFG", "HIJG", true, 1234);
        A.agregar(A1.toString(), "avion.txt");
        A.agregar(A2.toString(), "avion.txt");
        A.agregar(AE.toString(), "aereopuerto.txt");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipalFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestionAreolineas;
    private javax.swing.JButton btnGestionAreopuertos;
    private javax.swing.JButton btnGestionAviones;
    private javax.swing.JButton btnGestionVuelos;
    private javax.swing.JLabel imgMenuAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuSalir;
    // End of variables declaration//GEN-END:variables
}
